"""Restore the iv3 dataset from the fixture that ships with the code.

This is the deploy step — `migrate` builds the tables, this fills them:

    python manage.py migrate && python manage.py load_iv3_data

It reads nothing but iv3/fixtures/iv3_data.json.gz, so it needs no warehouse and no
network. The fixture is regenerated by hand when CBS publishes; see sync_iv3_summary.
"""

from django.core.management import call_command
from django.core.management.base import BaseCommand
from django.db import transaction

from iv3.models import Gemeente, Inwoners, Iv3Summary, Iv3Taakveld

FIXTURE = "iv3_data"

# The four data models the fixture is *for*. Order is irrelevant — they have no foreign keys
# between them; the dashboard joins them in Python on (jaar, gm_code).
MODELS = (Iv3Summary, Iv3Taakveld, Gemeente, Inwoners)

# The fixture is a `dumpdata iv3`, so it also carries the two configuration models — the sixteen
# Measure rows and the DashboardSettings singleton. Those are not data, they are settings an
# admin edits from /instellingen, and reloading them on deploy is wrong twice over:
#
#   * It silently reverts every edited formula and every changed setting, so a redeploy quietly
#     undoes an admin's work with nothing in the output to say so.
#   * It can fail outright. "Standaardwaarden herstellen" used to delete the Measure rows and
#     re-insert them, which gave them fresh autoincrement pks. loaddata matches on pk, so the
#     fixture's pk 1-16 would then insert *alongside* rows holding the same keys and hit the
#     unique constraint on Measure.key — an IntegrityError in the middle of a deploy.
#
# So they are excluded here and seeded by init_measures below instead, which inserts only what
# is missing. A fresh database still ends up with all sixteen; a populated one keeps its edits.
CONFIG_MODELS = ("iv3.measure", "iv3.dashboardsettings")


class Command(BaseCommand):
    help = "Load the iv3 dataset from the shipped fixture. Run this on deploy, after migrate."

    def add_arguments(self, parser):
        parser.add_argument(
            "--skip-if-loaded",
            action="store_true",
            help="Skip loading if iv3 data is already present in the database.",
        )

    def handle(self, *args, **options):
        if options["skip_if_loaded"] and Iv3Summary.objects.exists():
            self.stdout.write("iv3 data already present, skipping load")
            return
        # The delete is what makes this idempotent, and it is not optional. loaddata matches
        # existing rows by primary key, but these tables are rebuilt by delete-then-insert in
        # sync_iv3_summary, so a regenerated fixture carries a fresh set of autoincrement pks.
        # Loading it over a populated database would therefore *insert alongside* the old rows
        # rather than replace them — 6398 summary rows would quietly become 12796, and every
        # per-inwoner figure drawn from them would halve. Emptying first means the fixture is
        # the whole truth, every time, which is also what makes redeploying safe.
        with transaction.atomic():
            for model in MODELS:
                model.objects.all().delete()
            call_command("loaddata", FIXTURE, exclude=list(CONFIG_MODELS), verbosity=0)
            # Insert-only, so this is what seeds a fresh database without disturbing a
            # populated one. See CONFIG_MODELS.
            call_command("init_measures", verbosity=0)

        for model in MODELS:
            self.stdout.write(f"{model.objects.count():6} {model.__name__}")
        self.stdout.write(self.style.SUCCESS("iv3 dataset geladen"))
