"""Restore the iv3 dataset from the fixture that ships with the code.

This is the deploy step — `migrate` builds the tables, this fills them:

    python manage.py migrate && python manage.py load_iv3_data

It reads nothing but iv3/fixtures/iv3_data.json.gz, so it needs no warehouse and no
network. The fixture is regenerated by hand when CBS publishes; see sync_iv3_summary.
"""

from django.core.management import call_command
from django.core.management.base import BaseCommand
from django.db import transaction

from iv3.models import Gemeente, Inwoners, Iv3Summary, Iv3Taakveld

FIXTURE = "iv3_data"

# Everything the fixture carries. Order is irrelevant — these four models have no foreign
# keys between them; the dashboard joins them in Python on (jaar, gm_code).
MODELS = (Iv3Summary, Iv3Taakveld, Gemeente, Inwoners)


class Command(BaseCommand):
    help = "Load the iv3 dataset from the shipped fixture. Run this on deploy, after migrate."

    def handle(self, *args, **options):
        # The delete is what makes this idempotent, and it is not optional. loaddata matches
        # existing rows by primary key, but these tables are rebuilt by delete-then-insert in
        # sync_iv3_summary, so a regenerated fixture carries a fresh set of autoincrement pks.
        # Loading it over a populated database would therefore *insert alongside* the old rows
        # rather than replace them — 6398 summary rows would quietly become 12796, and every
        # per-inwoner figure drawn from them would halve. Emptying first means the fixture is
        # the whole truth, every time, which is also what makes redeploying safe.
        with transaction.atomic():
            for model in MODELS:
                model.objects.all().delete()
            call_command("loaddata", FIXTURE, verbosity=0)

        for model in MODELS:
            self.stdout.write(f"{model.objects.count():6} {model.__name__}")
        self.stdout.write(self.style.SUCCESS("iv3 dataset geladen"))
