# Generated by Django 5.2.2 on 2026-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gemeente',
            fields=[
                ('pk', models.CompositePrimaryKey('gm_code', 'jaar', blank=True, editable=False, primary_key=True, serialize=False)),
                ('gm_code', models.CharField(db_column='gm_code', max_length=16)),
                ('gm_naam', models.CharField(db_column='gm_naam', max_length=255)),
                ('prv_code', models.BigIntegerField(db_column='prv_code', null=True)),
                ('jaar', models.IntegerField()),
            ],
            options={
                'db_table': 'gemeenten',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GemeenteIv3',
            fields=[
                ('pk', models.CompositePrimaryKey('taakveldbalanspost', 'categorie', 'gemeenten', 'jaar', 'verslagsoort', blank=True, editable=False, primary_key=True, serialize=False)),
                ('taakveldbalanspost', models.TextField()),
                ('categorie', models.TextField()),
                ('gemeenten', models.TextField()),
                ('jaar', models.SmallIntegerField()),
                ('verslagsoort', models.TextField()),
                ('eerste_plaatsing', models.FloatField(db_column='1eplaatsing', null=True)),
                ('tweede_plaatsing', models.FloatField(db_column='2eplaatsing', null=True)),
            ],
            options={
                'db_table': 'gemeenten_iv3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inwoners',
            fields=[
                ('pk', models.CompositePrimaryKey('gemeente', 'jaar', blank=True, editable=False, primary_key=True, serialize=False)),
                ('gemeente', models.TextField()),
                ('jaar', models.BigIntegerField()),
                ('aantal_inwoners', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'inwoners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iv3Meta',
            fields=[
                ('titel', models.TextField(primary_key=True, serialize=False)),
                ('kolom_kurtosis', models.TextField(null=True)),
                ('kolom_cbs', models.TextField(null=True)),
                ('beschrijving', models.TextField(null=True)),
            ],
            options={
                'db_table': 'gemeenten_iv3_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iv3Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.IntegerField()),
                ('verslagsoort', models.CharField(max_length=16)),
                ('gm_code', models.CharField(max_length=16)),
                ('inwoners', models.IntegerField(null=True)),
                ('lasten', models.FloatField(default=0)),
                ('baten', models.FloatField(default=0)),
                ('reserve_lasten', models.FloatField(default=0)),
                ('reserve_baten', models.FloatField(default=0)),
                ('sociaal', models.FloatField(default=0)),
                ('salarissen', models.FloatField(default=0)),
                ('inhuur', models.FloatField(default=0)),
                ('verbonden', models.FloatField(default=0)),
                ('rijk', models.FloatField(default=0)),
                ('spuks', models.FloatField(default=0)),
                ('heffingen', models.FloatField(default=0)),
                ('per_hoofdcategorie', models.JSONField(default=dict)),
                ('per_hoofdtaakveld', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['jaar', 'verslagsoort'], name='iv3_iv3summ_jaar_524183_idx')],
                'constraints': [models.UniqueConstraint(fields=('jaar', 'verslagsoort', 'gm_code'), name='unique_iv3_summary_row')],
            },
        ),
    ]
