# Generated by Django 5.2.2 on 2026-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iv3summary',
            name='personeel_per_hoofdtaakveld',
            field=models.JSONField(default=dict),
        ),
    ]
