# Generated by Django 5.2.2 on 2026-07-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0002_iv3summary_personeel_per_hoofdtaakveld'),
    ]

    operations = [
        migrations.AddField(
            model_name='iv3summary',
            name='baten_heffingen_per_categorie',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='overige_baten_per_hoofdcategorie',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='reserve_baten_per_hoofdcategorie',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='spuks_per_hoofdtaakveld',
            field=models.JSONField(default=dict),
        ),
    ]
