# Generated by Django 5.2.2 on 2026-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0003_baten_breakdowns'),
    ]

    operations = [
        migrations.AddField(
            model_name='iv3summary',
            name='lasten_per_hoofdtaakveld_categorie',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='lasten_per_taakveld',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='reserve_lasten_per_hoofdcategorie',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Iv3Taakveld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.IntegerField()),
                ('code', models.CharField(max_length=16)),
                ('titel', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['jaar', 'code'],
                'constraints': [models.UniqueConstraint(fields=('jaar', 'code'), name='unique_iv3_taakveld_row')],
            },
        ),
    ]
