# Generated by Django 5.2.2 on 2026-07-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0004_lasten_breakdowns'),
    ]

    operations = [
        migrations.AddField(
            model_name='iv3summary',
            name='balanstotaal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='eigen_vermogen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='inhuur_overhead',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='salarissen_overhead',
            field=models.FloatField(default=0),
        ),
    ]
