# Generated by Django 5.2.2 on 2026-07-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0006_iv3_eigen_tabellen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpi_per_jaar', models.JSONField(blank=True, default=dict)),
                ('cao_lonen_per_jaar', models.JSONField(blank=True, default=dict)),
                ('inwonergroepen', models.JSONField(blank=True, default=list)),
                ('aggregation_method', models.CharField(choices=[('equal_weight', 'Equal-weight mean'), ('population_weighted', 'Population-weighted mean')], default='equal_weight', max_length=32)),
                ('taakveld_label_overrides', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Dashboard-instellingen',
                'verbose_name_plural': 'Dashboard-instellingen',
            },
        ),
    ]
