# Generated by Django 5.2.2 on 2026-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0007_dashboardsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('expression', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('page', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
