# Generated by Django 5.2.2 on 2026-07-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0008_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='iv3summary',
            name='baten_heffingen_per_taakveld',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='overige_baten_grond_huren',
            field=models.JSONField(default=dict),
        ),
    ]
