# Generated by Django 5.2.2 on 2026-07-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0009_iv3summary_baten_heffingen_per_taakveld_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iv3summary',
            name='lasten_naamloze_taakvelden',
            field=models.FloatField(default=0.0),
        ),
    ]
