# Generated by Django 5.2.2 on 2026-07-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0010_iv3summary_lasten_naamloze_taakvelden'),
    ]

    operations = [
        migrations.AddField(
            model_name='iv3summary',
            name='resultaat_lasten_per_hoofdcategorie',
            field=models.JSONField(default=dict),
        ),
    ]
