# Generated by Django 5.2.2 on 2026-07-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0011_iv3summary_resultaat_lasten_per_hoofdcategorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iv3summary',
            name='lasten_naamloze_taakvelden',
        ),
        migrations.AddField(
            model_name='iv3summary',
            name='naamloze_lasten_per_hoofdcategorie',
            field=models.JSONField(default=dict),
        ),
    ]
