# Generated by Django 5.2.2 on 2026-08-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0012_remove_iv3summary_lasten_naamloze_taakvelden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inwoners',
            options={'verbose_name': 'Inwoners', 'verbose_name_plural': 'Inwoners'},
        ),
    ]
