# Generated by Django 5.2.2 on 2026-08-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iv3', '0013_alter_inwoners_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gemeente',
            options={'verbose_name': 'Gemeente', 'verbose_name_plural': 'Gemeenten'},
        ),
        migrations.AlterModelOptions(
            name='iv3summary',
            options={'verbose_name': 'IV3-samenvatting', 'verbose_name_plural': 'IV3-samenvattingen'},
        ),
        migrations.AlterModelOptions(
            name='iv3taakveld',
            options={'ordering': ['jaar', 'code'], 'verbose_name': 'IV3-taakveld', 'verbose_name_plural': 'IV3-taakvelden'},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'ordering': ['key'], 'verbose_name': 'Formule', 'verbose_name_plural': 'Formules'},
        ),
    ]
