"""Turn nederland_map.svg into a TypeScript data module. Run: npm run generate:map

The Illustrator export mixes <path d>, <polygon points> and <g> groups of both. React
wants one <path d> per gemeente, so polygons become M/L/Z subpaths and a group's children
are concatenated into a single multi-subpath d.

The 352 shapes are exactly the 2021 gemeente-indeling — verified against the IV3 database,
which lists precisely these 352 codes for 2021 and no others.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src/assets/icons/nederland_map.svg"
OUT = ROOT / "src/features/referentiegroep/data/gemeente-shapes.ts"

#: The gemeente-indeling the source SVG was drawn in.
SHAPE_JAAR = 2021

svg = SRC.read_text()

viewbox = re.search(r'viewBox="([^"]+)"', svg).group(1)


def polygon_to_d(points: str) -> str:
    """`points="x,y x,y"` -> `M x,y L x,y Z`. Illustrator emits no stray whitespace."""
    coords = points.split()
    return "M" + coords[0] + "L" + "L".join(coords[1:]) + "Z"


def children_d(inner: str) -> str:
    """Every path/polygon inside a <g>, concatenated in document order."""
    parts = []
    for m in re.finditer(r'<(path|polygon)\b[^>]*?(?:\sd="([^"]+)"|\spoints="([^"]+)")[^>]*/>', inner, re.S):
        kind, d, points = m.group(1), m.group(2), m.group(3)
        parts.append(d if kind == "path" else polygon_to_d(points))
    return "".join(parts)


shapes: list[tuple[str, str]] = []

# Groups first, then remove them so their children are not also picked up as top-level.
rest = svg
for m in re.finditer(r'<g id="(GM\d+)"[^>]*>(.*?)</g>', svg, re.S):
    shapes.append((m.group(1), children_d(m.group(2))))
rest = re.sub(r'<g id="GM\d+"[^>]*>.*?</g>', "", svg, flags=re.S)

for m in re.finditer(r'<path id="(GM\d+)"[^>]*\sd="([^"]+)"[^>]*/>', rest, re.S):
    shapes.append((m.group(1), m.group(2)))

for m in re.finditer(r'<polygon id="(GM\d+)"[^>]*\spoints="([^"]+)"[^>]*/>', rest, re.S):
    shapes.append((m.group(1), polygon_to_d(m.group(2))))

# Collapse the newlines Illustrator wraps long d attributes with.
shapes = [(code, re.sub(r"\s+", " ", d).strip()) for code, d in shapes]
shapes.sort(key=lambda s: s[0])

# Fail loudly rather than emit a broken map. Concatenating a group's children into one `d`
# is only lossless because every subpath re-anchors with an absolute M and nothing carries
# a transform — so those are the two assumptions worth asserting.
assert len(shapes) == 352, f"expected 352 shapes (the 2021 indeling), got {len(shapes)}"
assert len({c for c, _ in shapes}) == 352, "duplicate gm_codes"
assert all(d for _, d in shapes), "a shape came out with empty path data"
assert all(d.startswith("M") for _, d in shapes), "a path does not start with an absolute M"
assert "transform=" not in svg, "the SVG carries a transform; flattening would move shapes"

body = "\n".join(f'    ["{code}", "{d}"],' for code, d in shapes)

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    f'''/**
 * The gemeente outlines of nederland_map.svg, as plain path data.
 *
 * Generated by `scripts/extract-gemeente-shapes.py` from
 * `src/assets/icons/nederland_map.svg` — do not edit by hand. The source is an Illustrator
 * export that mixes <path>, <polygon> and <g> groups; this module flattens all three into
 * one path `d` per gemeente so the map can render each as a React <path> with its own
 * colour and click handler.
 *
 * These {len(shapes)} outlines are exactly the {len(shapes)} gemeenten that existed in {SHAPE_JAAR} — the
 * match is exact in both directions, which is what makes gemeente-mergers.ts able to
 * reconcile later years onto them.
 */

/** The coordinate space every `d` below is drawn in. */
export const MAP_VIEWBOX = "{viewbox}";
export const MAP_WIDTH = {viewbox.split()[2]};
export const MAP_HEIGHT = {viewbox.split()[3]};

/** The gemeente-indeling these outlines are drawn in. See gemeente-mergers.ts. */
export const SHAPE_JAAR = {SHAPE_JAAR};

/** [gm_code, path d], sorted by code. */
export const GEMEENTE_SHAPES: ReadonlyArray<readonly [string, string]> = [
{body}
];
'''
)

print(f"wrote {len(shapes)} shapes -> {OUT}")
print(f"viewBox: {viewbox}")
print(f"file size: {OUT.stat().st_size / 1024:.0f}K")
