# Generated by Django 5.2.2 on 2026-08-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_invite_twofactorcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invite",
        ),
    ]
